name: MineAI
main: com.mcmod.ai.MCAIPlugin
version: 1.0.5
api-version: 1.20
commands:
  api:
    description: Google AI API anahtarını ayarla
    usage: /api <anahtar>
  model:
    description: Model seç
    usage: /model <model_ismi>
  ai:
    description: Yapay zeka ile konuş
    usage: /ai <mesaj>
  aihelp:
    description: MCAI eklentisi yardım komutu
    usage: /aihelp
name: MineAI
